#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch_name=$(git rev-parse --abbrev-ref HEAD)

if [ "$branch_name" = "main" ]; then
  echo "You cannot commit directly to the main branch. Please use a feature branch and open a pull request."
  exit 1
fi



npx lint-staged

